### ISSUE TITLE
补全文档

### ISSUE THREAD

**Issue by biezhi** [peachdocs/peach#1]
我想看看文档呢，对go不是很熟，好像是一个搭建web文档的东西.
不知道怎么使用

**Comment by Unknwon** [comment]
第一个版本的代码写完了，但是文档还没时间，会尽快补上的。。。虽然我自己已经用上了。。:sweat_smile:

**Comment by biezhi** [comment]
期待ing，我也要试试呢~ 辛苦了

**Comment by Unknwon** [comment]
http://peachdocs.org/ 文档已上线~

**Comment by biezhi** [comment]
(๑• . •๑) good～

**Comment by biezhi** [comment]
希望可以出静态html版本，我觉得部署起来好麻烦

**Comment by Unknwon** [comment]
静态HTML只是为了提升响应速度。。还是要部署的


现在需要源码编译确实麻烦 等第一个稳定版出来就有二进制了

**Comment by biezhi** [comment]
类似hexo 可以有一个命令生成html,我把静态资源拖到web服务器即可

**Comment by Unknwon** [comment]
那个和peach的目的不一样 不能做现在这么方便的多语言以及未来更多的搜索优化

**Comment by biezhi** [comment]
我明白了，peach注重服务。好吧 我借鉴你的ui用java实现一个web文档生成器

**Comment by Unknwon** [comment]
哈哈～留个友链那就更好了

**Comment by biezhi** [comment]
(´・ω・`)  会的
