### ISSUE TITLE
增加Http basic访问权限对部分URL进行保护

### ISSUE THREAD

**Issue by raistlinzx** [peachdocs/peach#11]
对部分资源进行保护，指定用户访问。其他资源开放。
比如：增加一个security.ini配置，类似TOC.ini
```
[user]
username=passwd
xxx=xxxxxx

[auth]
/URL/PATH=username,username2
/URL/PATH2=username,username2
```

**Comment by Unknwon** [comment]
嗯。。感觉可以用。。能不能说下使用场景？

**Comment by raistlinzx** [comment]
主要还是用于内部文档访问，比如公共部分API/产品文档，开放所有用户访问；部分需要保密的文档，只能部分用户访问。
# 一些不成熟的思路
### 保存所有用户名密码
有一个`user.ini`记录所有用户名及密码，可以采用`htpasswd`命令生成，如：
```shellscript
htpasswd -c user.ini admin
```
保存文件user.ini内容如：
```text
admin:$apr1$kv8aJjHx$cF53jBhJxteGO7ZGdTVQD.
```
### URL保护资源及白名单
比如`auth.ini`，里面记录所有被保护的URL，以及允许该URL的白名单用户名
```text
/doc/secureDoc=admin
```
只要添加到auth.ini中得URL资源才会被保护，其余所有URL都开放访问。 

### 其他
- 不需要注册，所有用户都由user.ini指定
- 不需要增加登录页，登录操作全部由Http BasicAuth处理了。

**Comment by Unknwon** [comment]
- 密码保存可以统一使用 `用户名:MD5密码`
- 至于资源的权限，直接使用 `/doc/secureDoc=admin,user1,user2` 这样好像也可以。

要是没有其他意见的话，我抽空把它实现了？ :trollface:

**Comment by raistlinzx** [comment]
没有问题，thx！

**Comment by Unknwon** [comment]
好了，和 TOC.ini 同一个目录，放置 `protect.ini` 就可以实现这个需求。

样例文件：

```ini
[user]
user1 = 5F4DCC3B5AA765D61D8327DEB882CF99

[auth]
installation/install_from_binary = user1
```

其中，用户密码为 MD5 编码结果，`auth` 里 URL 不需要携带 `/docs/` 前缀。

**Comment by raistlinzx** [comment]
COOL!

**Comment by Unknwon** [comment]
额。。测试过了嘛？过了我顺便把文档写了

**Comment by raistlinzx** [comment]
测试OK，非常好用

**Comment by Unknwon** [comment]
好的 :trollface:

**Comment by Unknwon** [comment]
http://peachdocs.org/docs/howto/protect_resources
