### ISSUE TITLE
run by docker

### ISSUE THREAD

**Issue by allustin** [peachdocs/peach#13]
it is useful to run peachdocs by docker image with docs dir mount

like this or something like this

```
docker pull peachdocs:latest
docker run -v ./opt/my.peach:/opt/peachdoc  peachdocs:latest --name=my-docs-container
```

thats why we need Dockerfile example (may be) or offical image for peachdoc

**Comment by Unknwon** [comment]
Thanks your advice!

**Comment by allustin** [comment]
i have just create first working version for my docs site

https://gist.github.com/allustin/3aa6c8e937186ba70642

i have not implemented entrypoint and always rebuild it from peach source, but it is working now.

P.S. Some code is have been get from gogs docker file ;-)

**Comment by Unknwon** [comment]
Aha, that's clever! Thanks!
