### ISSUE TITLE
支持多个peach文档库

### ISSUE THREAD

**Issue by fengmu** [peachdocs/peach#18]
localhost:5556/docs 访问的是缺省的文档仓库，是第0个仓库。不知是否支持多个文档仓库，如下列用法：
localhost:5556/docs1 访问第1个仓库，localhost:5556/docs2 访问第2个仓库。这样使用可适应多主题的大型文档。

**Comment by Unknwon** [comment]
和这个 issue 重复了。。 https://github.com/peachdocs/peach/issues/12

**Comment by fengmu** [comment]
明白了。
