### ISSUE TITLE
Adding next / previous buttons

### ISSUE THREAD

**Issue by digitalcraftsman** [peachdocs/peach#20]
Hi @Unknwon,

it would be useful to have a next and previous button at the bottom of each page in the documentation. This way users don't need to scroll back to the top on longer pages and look for the next page in the sidebar.

**Comment by Unknwon** [comment]
Thanks your feedback!

This is indeed a helpful feature, I will think about it.

**Comment by digitalcraftsman** [comment]
Thanks for your fast reaction :+1:

**Comment by Unknwon** [comment]
I have very limited time for developing new features, so you may need to wait for fairly long time.
