### ISSUE TITLE
GitLab webhooks not triggering website update. 

### ISSUE THREAD

**Issue by levibostian** [peachdocs/peach#24]
I have setup peachdocs on my remote server and everything is running excellent with a GitHub repo. Push updated documentation up to the GitHub repo, webhook triggers, updates my peachdocs instance on my remote web server. 

I have been playing around with other git services besides GitHub. More specifically, GitLab. 

I need my git remote server to be hosted privately. Password protecting peachdocs is great but I also need my git remote server repo to be hosted privately as well. For this purpose, I have been using GitLab for my private repo hosting. 

I take my peachdocs website that is working 100% with GitHub, I change my remote git server from github to gitlab in the custom/app.ini file, I create my GitLab repo (create it public first just to try it out then I'll switch to private repo with deploy hook), create a webhook, remove my `data/docs` directory, then run peachdocs. 

I push my code up to GitLab, the webhook runs successfully and in my peachdocs logs I see that the webhook is "completed successfully" just like it does with GitHub. Everything is working *exactly* the same as GitHub. 

However, when I refresh my browser, I don't see any documentation. Peachdocs does not pull down the GitLab project and display it to me. 

Does peachdocs work with any other git repo service besides GitHub? I was looking at the source but didn't find anything specific to GitHub.

**Comment by Unknwon** [comment]
Hi, Peach works any POST request with correct secret value, so even a fake POST tool could work.

I think the problem is you're having private GitLab instance and I suppose Peach does not know the username and password for HTTP basic auth and thus hangs?

**Comment by levibostian** [comment]
I am actually using a public GitLab repo. I am using public for now to test if it works then move on making it private.

**Comment by Unknwon** [comment]
What response does GitLab webhook get back?

**Comment by levibostian** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md

**Comment by Unknwon** [comment]
No, I'm asking you what do you see for responses of your webhook.

**Comment by levibostian** [comment]
Response shows a macaron message saying it processed a successful webhook
response.

**Comment by Unknwon** [comment]
@levibostian you need to check Peach console output.

**Comment by royalterra** [comment]
UHm I have the seam issue Test with Github and Gogs Both say connection OK 200 
But I not see any Updates is not changes at all

**Comment by Unknwon** [comment]
@royalterra have you gave the proper permission to the server that runs Peach?
