### ISSUE TITLE
能否打通自家的gogs？

### ISSUE THREAD

**Issue by Veitor** [peachdocs/peach#32]
我们团队正在使用gogs，一些项目以及md文档都在上面。但开启了REQUIRE_SIGNIN_VIEW，需要登录才能访问。
在peach设置远程git地址时，感觉没用了啊。。。
这个看看能不能有什么方法进行配置，以打通gogs

**Comment by Unknwon** [comment]
这是你配置的问题啊 服务器生成一个ssh key然后加到仓库作为部署密钥就行 最后用ssh地址作为源
