### ISSUE TITLE
增设登录功能用于完全内部文档库

### ISSUE THREAD

**Issue by MiyamuraMiyako** [peachdocs/peach#38]
就像gogs可以设置必须登录才允许访问内部一样。peach现有的```保护内部资源```不足以完成这个任务。

**Comment by Unknwon** [comment]
这个需求有点高级了呀。。不过可以是对 go 插件开发的一次尝试。。

**Comment by Unknwon** [comment]
我觉得完整的登录功能有点复杂了，还要自带管理，准备就只做 LDAP 方面的支持了 https://github.com/peachdocs/peach/issues/31
