### ISSUE TITLE
Add openssh-client to docker image.

### ISSUE THREAD

**Issue by rhalff** [peachdocs/peach#48]
I'm linking a documentation repository stored on a gogs server to peachdocs and
I want to connect to the instance using ssh.

Currently the docker image does not include the ssh client:

```
[Peach] 18-07-21 16:44:33 [FATAL] Fail to init docs:
Fail to update docs from remote source(git@gogs-server:rhalff/docs.git):
exit status 1 - error: cannot run ssh: No such file or directory

fatal: unable to fork
```

If docker installs the `openssh-client` package this issue will be gone. 

https://github.com/peachdocs/peach/blob/master/Dockerfile#L7

**Comment by Unknwon** [comment]
Fixed by #49.
