### ISSUE TITLE
新的peach演示站点

### ISSUE THREAD

**Issue by biezhi** [peachdocs/peach#5]
* 文档站点：http://bladejava.com
* 配置：https://github.com/bladejava/blade.peach
* 文档：https://github.com/bladejava/docs

**Comment by Unknwon** [comment]
哈哈！好酷炫！马上加到文档

**Comment by Unknwon** [comment]
话说你的 peach 的默认css好像没更新 

http://bladejava.com/docs `Blade` 上方的空白应该是被去掉了得

**Comment by Unknwon** [comment]
已更新：http://peachdocs.org/docs

**Comment by biezhi** [comment]
好的，我更新试试 :joy: 下方LOGO没人设计，瞎搞了一个放上去，自己觉得挺顺眼的。

**Comment by Unknwon** [comment]
Peach 的 Logo 更扯淡。。不要慌。。:trollface:

**Comment by biezhi** [comment]
:full_moon_with_face: 第一眼看到认为是个逗比 差点没笑出来

**Comment by Unknwon** [comment]
哈哈哈哈 :joy:

快把多说的 PR 过来吧~

**Comment by biezhi** [comment]
你把变量名写在这个页面 http://peachdocs.org/docs/howto/extension 就ok了

**Comment by biezhi** [comment]
`EnableDuoShuo`
`DuoShuoTplPath`
`DuoShuoShortName`

**Comment by Unknwon** [comment]
你先把 HTML pr 过来。。我改完代码后会加上的 :trollface:
