### ISSUE TITLE
Docker FATAL about custom/app.ini

### ISSUE THREAD

**Issue by icaics** [peachdocs/peach#50]
Hi,

When I use 
```
$ docker run --name=peach -p 5555:5555 -v /docker/peach/data:/data/peach peachdocs/peach
```
to start docker, log says 
```
[Peach] 18-07-27 02:18:49 [FATAL] No custom configuration found: 'custom/app.ini'
```
and it can't start

trid to `mkdir custom` and add `app.ini` and `mkdir locale` and add EN CN file,
but it seems that the `locale` folder is not in the correct folder
log says can't find `local -`

in the document says 
```
# Peach will complain about missing custom app.ini, leave it there and see Settings section below.
```
but the `Settings` section is empty.

Where can I find some information ?

Thank you.

**Comment by Unknwon** [comment]
Ah, sorry about documentation mistake. The first time start without `custom/app.ini` is meant to fail. You can create it in the volumed directory on your host system. Note that the volumed directory is already the "custom" directory, so you should directly create a new file named "app.ini" without a extra layer.
