### ISSUE TITLE
自己创建文档的路径配置怎么都不对

### ISSUE THREAD

**Issue by taopoppy** [peachdocs/peach#60]
// custom/app.ini的配置
[docs]
TYPE = local
TARGET = mydocs

然后mydocs和custom是同级目录

**Comment by unknwon** [comment]
`TARGET` 写绝对路径试试？

**Comment by taopoppy** [comment]
写一个文件名就行，再问一下，怎么加robots.txt文件

**Comment by taopoppy** [comment]
我加好了，直接加到public下面
