### ISSUE TITLE
Semantic-UI google 字体问题

### ISSUE THREAD

**Issue by hho2002** [peachdocs/peach#9]
Semantic-UI 使用了 google 字体，导致国内访问很慢

> @import url(https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin);

建议替换为本地字体

> https://google-webfonts-helper.herokuapp.com/fonts/lato?subsets=latin

**Comment by Unknwon** [comment]
你可以直接替换掉默认的 CSS。。导入一个自定义版的 http://peachdocs.org/docs/howto/static_resources#%E8%87%AA%E5%AE%9A%E4%B9%89-ui-%E6%A1%86%E6%9E%B6
